# Generated by Django 2.1.7 on 2019-03-06 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id_no', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='pictures')),
                ('optionA', models.TextField()),
                ('optionB', models.TextField()),
                ('optionC', models.TextField()),
                ('optionD', models.TextField()),
                ('correct_choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQ1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal.Section1')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQ2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal.Section2')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedQ3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('id_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal.Section3')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.PositiveIntegerField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Time1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('id_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('id_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Time3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, max_length=100)),
                ('id_no', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
